### ISSUE TITLE
ValueError: Columns must be same length as key

### ISSUE THREAD

**Issue by clarkenj** [SIMEXP/giga_auto_qc#14]
So it gets some way to completion on CIMA-Q (progress!) but I am getting an error, and no file produced.

Contents of .out:
```
/home/nclarke/scratch/cimaq_fmriprep-20.2.7lts_1687549726/CIMAQ
Namespace(bids_dir=PosixPath('/home/nclarke/scratch/cimaq_fmriprep-20.2.7lts_1687549726/CIMAQ/fmriprep-20.2.7lts'), output_dir=PosixPath('/lustre04/scratch/nclarke/cimaq_qc'), analysis_level='participant', participant_label=None, session=None, task=None, quality_control_parameters=None, reindex_bids=False, verbose=1)
Quality control parameters: {'mean_fd': 0.55, 'scrubbing_fd': 0.2, 'proportion_kept': 0.5, 'anatomical_dice': 0.97, 'functional_dice': 0.89}
Retrieved anatomical reference mask
Use standard template as functional scan reference.
Calculate the anatomical dice score.
task-memory
Calculate motion QC...
Calculate EPI mask dice...
170 out of 384 functional scans passed automatic QC.
```
Contents of .err (posting first part as a screenshot):
![Screenshot 2023-07-10 at 16 32 25](https://github.com/SIMEXP/giga_auto_qc/assets/57987005/36e5ba62-5494-4677-a926-1448db35b94f)
followed by:
```
Traceback (most recent call last):
  File "/home/nclarke/.local/bin/giga_auto_qc", line 8, in <module>
    sys.exit(main())
  File "/lustre03/project/6003287/nclarke/giga_preprocess2/giga_auto_qc/giga_auto_qc/run.py", line 79, in main
    workflow(args)
  File "/lustre03/project/6003287/nclarke/giga_preprocess2/giga_auto_qc/giga_auto_qc/workflow.py", line 95, in workflow
    metrics = utils.parse_scan_information(metrics)
  File "/lustre03/project/6003287/nclarke/giga_preprocess2/giga_auto_qc/giga_auto_qc/utils.py", line 69, in parse_scan_information
    identifiers[headers] = identifiers["identifier"].str.split(
  File "/home/nclarke/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 3947, in __setitem__
    self._setitem_array(key, value)
  File "/home/nclarke/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 3989, in _setitem_array
    check_key_length(self.columns, key, value)
  File "/home/nclarke/.local/lib/python3.10/site-packages/pandas/core/indexers/utils.py", line 392, in check_key_length
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
```

Can you help? Thanks so much!

**Comment by htwangtw** [comment]
Can you give me an example of the CIMAQ subject file name?
It's either they are not fitting BIDS standard or the pattern I used was not permissive enough. 
This is likely something we need to fix with a PR

**Comment by htwangtw** [comment]
Sorry, I was not clear. I meant fMRIPrep outputs. 
The QC tool is reading not reading the original BIDS data so it's not relevant in this context. 

Also after some thinking - do you mind checking if all subject's bold file has the same set of [BIDS entities](https://bids-specification.readthedocs.io/en/stable/appendices/entities.html)? For example, are there subjects with `run` while others don't? It could be anything.
If this is the case than I have an idea what is going wrong and that can be fixed without looking at the data.

**Comment by clarkenj** [comment]
Ah yes of course, sorry. Here's an example: `sub-7538204_ses-V03_task-rest_space-MNI152NLin2009cAsym_desc-aseg_dseg.nii.gz`. Is the `_space` part odd? 

Yes some have multiple runs and others don't (so, no `run`).

**Comment by htwangtw** [comment]
> Yes some have multiple runs and others don't (so, no `run`).

Great we found the issue!

I know what to do to fix this now

**Comment by clarkenj** [comment]
Thank you so much @htwangtw !!
