### ISSUE TITLE
--reindex-bids not recognized

### ISSUE THREAD

**Issue by clarkenj** [SIMEXP/giga_auto_qc#5]
When I run  `giga_auto_qc /home/nclarke/scratch/COBRE/fmriprep-20.2.7lts /home/nclarke/scratch/COBRE/giga_auto_qc_output participant --reindex-bids` I get the following error:

```
usage: giga_auto_qc [-h] [--participant_label PARTICIPANT_LABEL [PARTICIPANT_LABEL ...]] [--session SESSION [SESSION ...]]
                    [--task TASK [TASK ...]] [--quality_control_parameters QUALITY_CONTROL_PARAMETERS]
                    bids_dir output_dir {participant,group}
giga_auto_qc: error: unrecognized arguments: --reindex-bids
```

I have checked the branch is up to date, and the flag is showing in the README. I also tried the order `giga_auto_qc --reindex-bids` and got the same error (I don't know if that should make a difference). When I run `giga_auto_qc -h` it isn't listed as an argument.

**Comment by htwangtw** [comment]
Have you installed the latest version by pulling the latest main branch?

**Comment by clarkenj** [comment]
Yep

**Comment by htwangtw** [comment]
If you cannot see that option then it's not.
Can you do the following for me:

```
cd /path/to/giga_auto_qc
git tag
```
and see if you can see 
```
0.1
0.2
```

**Comment by clarkenj** [comment]
Yes that is what I see when I run `git tag`

**Comment by htwangtw** [comment]
Can you do this?
```
git checkout 0.2
pip install -e .
```

**Comment by clarkenj** [comment]
Done. And then run the command?

**Comment by htwangtw** [comment]
yes

**Comment by clarkenj** [comment]
8be70c4b28ce725afb487391e923697171dc2a7d

**Comment by clarkenj** [comment]
Was just `Killed`. Would you have time to look at it in-person together this week? Maybe I'm doing something wrong

**Comment by htwangtw** [comment]
I have been indexing datasets with more subjects and can finish the job under one hour. I will have a look at some point.

**Comment by clarkenj** [comment]
Closing since the --reindex-bids flag is recognised, but will open a new issue for getting it to run
